### ISSUE TITLE
Is updating vector values supported?

### ISSUE THREAD

**Issue by mdogan** [jbellis/jvector#176]
I have an existing index and I want to update vector values of the some nodes. I'm updating values and calling `builder.addGraphNode(..)` for that nodes. This looks working when querying, but while saving and restoring index builder's data, it fails with `Nodes are added in the incorrect order!` assertion error. 

Is updating and re-adding existing node values supported? 

Test code:

```java
public static void main(String[] args) throws IOException {
    var vectors = SiftLoader.readFvecs("./siftsmall/siftsmall_base.fvecs");
    var ravv = new ListRandomAccessVectorValues(vectors, 128);

    // Initial build
    var builder = new GraphIndexBuilder<>(ravv, FLOAT32, COSINE, 16, 32, 1.4f, 1.5f);
    builder.build();

    // Update the first 1000 vector values
    // and re-index
    for (int i = 0; i < 1000; i++) {
        vectors.set(i, vectors.get(i+9000));
        builder.addGraphNode(i, ravv);
    }
    builder.cleanup();

    // Save builder state
    var fileName = "builder.dat";
    var out = new FileOutputStream(fileName);
    builder.getGraph().save(new DataOutputStream(out));
    out.close();

    // Restore builder state
    var builder2 = new GraphIndexBuilder<>(ravv, FLOAT32, COSINE, 16, 32, 1.4f, 1.5f);
    builder2.load(new SimpleMappedReader(fileName));
}
```

Final restore state step fails with:

```
java.lang.AssertionError: Nodes are added in the incorrect order! Comparing 0.9232595 to [0.78675026]
	at io.github.jbellis.jvector.graph.NodeArray.addInOrder(NodeArray.java:66)
	at io.github.jbellis.jvector.graph.GraphIndexBuilder.load(GraphIndexBuilder.java:620)
```

**Comment by jbellis** [comment]
No, it's not, because neighbors are computed based on the old vector, so changing it after that invalidates assumptions like the assert you're hitting.  But it should work to delete them, cleanup, and re-add them.

**Comment by mdogan** [comment]
Ah yes 🤦🏼 . Thanks, that works.
